// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV11Jfp3cOOcZr846dwWcSAy9Ye9aSMAk',
    appId: '1:34673716682:web:c4a5decb1a9501db253333',
    messagingSenderId: '34673716682',
    projectId: 'fitnest-app-828c4',
    authDomain: 'fitnest-app-828c4.firebaseapp.com',
    storageBucket: 'fitnest-app-828c4.firebasestorage.app',
    measurementId: 'G-E827S6M856',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi4eb0p0jGDRw_DF-GFQAFBWB5AX2zG84',
    appId: '1:34673716682:android:d9a5adc3a01893fc253333',
    messagingSenderId: '34673716682',
    projectId: 'fitnest-app-828c4',
    storageBucket: 'fitnest-app-828c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAggCvd0YpCMS7VBZlBQ8L8abnReEeFnRM',
    appId: '1:34673716682:ios:3a0c061865e767f7253333',
    messagingSenderId: '34673716682',
    projectId: 'fitnest-app-828c4',
    storageBucket: 'fitnest-app-828c4.firebasestorage.app',
    iosBundleId: 'com.example.fitnestApp',
  );
}
